### ISSUE TITLE
Cannot download pre-trained because not have Baidu account

### ISSUE THREAD

**Issue by RyanPham19092002** [GANWANSHUI/GaussianOcc#7]
Hi, thanks for your great works. But I have some issue when I download your pre-trained weight in Baidu (I cannot create account in Baidu because I don't have Chinese phone number, so I cannot download it from Baidu). Can you please upload pretrained model in google drive or another online storage ? 

Thanks for your help

**Comment by GANWANSHUI** [comment]
Hi, update with a Google link, please have a try.

**Comment by RyanPham19092002** [comment]
Hi, thanks for your reply.
My google account is phat.pham@isods.org, Can you share the pre-trained model via this google account ? 
Thank you

**Comment by GANWANSHUI** [comment]
You can download them directly

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: Phat Thanh Pham ***@***.***>
发送时间: Monday, August 26, 2024 11:59:11 PM
收件人: GANWANSHUI/GaussianOcc ***@***.***>
抄送: GANWANSHUI ***@***.***>; Comment ***@***.***>
主题: Re: [GANWANSHUI/GaussianOcc] Cannot download pre-trained because not have Baidu account (Issue #7)


Hi, thanks for your reply.
My google account is ***@***.******@***.***>, Can you share the pre-trained model via this google account ?
Thank you

―

**Comment by RyanPham19092002** [comment]
Hi, thanks for your reply, but I cannot access for this link you get.
It directs me to this website and I don't see where I can download pre-trained model
![image](https://github.com/user-attachments/assets/6896ec11-6452-4f7f-80e6-050fbbc742ac)
Do you have another ways to download pre-trained model ?  Thanks for your help

**Comment by GANWANSHUI** [comment]
https://drive.google.com/drive/u/0/mobile/folders/1ojxpFjj1bG4s5EiteLsqFnAz7liDhgq7

Could you visit this link?

**Comment by RyanPham19092002** [comment]
Oh thanks for your help, I can visit this google drive link.
Thank you so much
